// Writes WE Sign's icons from lib/icons/mapping.json: the Vue adapter app/javascript/icons/index.js (webpack resolves
// '@tabler/icons-vue' to it) and the Rails partials in app/views/icons. Run from the repository root after changing
// the mapping or adding an icon:
//
//   node lib/icons/generate.mjs [path to the @phosphor-icons/core package, default node_modules/@phosphor-icons/core]
//
// The icons are Phosphor Icons, Regular weight (MIT). It stops with a list when the code uses an icon that the mapping
// does not name, or when the mapping names a Phosphor icon that does not exist.
import fs from 'node:fs'
import path from 'node:path'

const core = process.argv[2] || 'node_modules/@phosphor-icons/core'
const { map, keep } = JSON.parse(fs.readFileSync('lib/icons/mapping.json', 'utf8'))
const kebab = (pascal) => pascal.replace(/([a-z])([A-Z0-9])/g, '$1-$2').replace(/([0-9])([A-Z])/g, '$1-$2').toLowerCase()
const pathData = (name) => {
  const file = path.join(core, 'assets/regular', `${name}.svg`)
  if (!fs.existsSync(file)) throw new Error(`no Phosphor icon "${name}" (${file})`)
  return fs.readFileSync(file, 'utf8').match(/<path d="([^"]+)"\/>/)[1]
}
const errors = []

// ---- Vue: every name imported from '@tabler/icons-vue' under app/javascript ----
const sources = fs.readdirSync('app/javascript', { recursive: true })
  .filter((f) => /\.(vue|js)$/.test(f) && !f.startsWith('icons'))
  .map((f) => fs.readFileSync(path.join('app/javascript', f), 'utf8'))
const vueNames = new Set()
for (const src of sources) {
  for (const m of src.matchAll(/import\s*{([^}]*)}\s*from\s*'@tabler\/icons-vue'/g)) {
    for (const n of m[1].split(',').map((s) => s.trim()).filter(Boolean)) vueNames.add(n)
  }
}
const lines = [...vueNames].sort().map((component) => {
  const name = kebab(component.replace(/^Icon/, ''))
  if (keep[name]) return `export { default as ${component} } from '@tabler/icons-vue/dist/esm/icons/${component}.js'`
  if (!map[name]) { errors.push(`Vue ${component} (${name}) is not in lib/icons/mapping.json`); return '' }
  return `export const ${component} = /* @__PURE__ */ icon('${name}', '${pathData(map[name])}')`
})

const adapter = `// Generated by lib/icons/generate.mjs from lib/icons/mapping.json: do not edit by hand.
// Phosphor Icons, Regular weight (https://phosphoricons.com), MIT licence, Copyright (c) 2023 Phosphor Icons.
// webpack resolves '@tabler/icons-vue' to this file (config/webpack/webpack.config.js), so the components keep their
// Tabler names, classes and props: size, width, height, color and class work as before; stroke props are ignored
// (Phosphor glyphs are filled shapes of one weight). Brand marks are Tabler's own components.
import { h } from 'vue'

const icon = (name, d) => (props, { attrs }) => {
  const { size, color, stroke, strokeWidth, 'stroke-width': strokeWidthAttr, ...rest } = attrs

  return h('svg', {
    xmlns: 'http://www.w3.org/2000/svg',
    width: size || 24,
    height: size || 24,
    viewBox: '0 0 256 256',
    fill: color || 'currentColor',
    ...rest,
    class: ['tabler-icon', \`tabler-icon-\${name}\`, 'ph-icon', attrs.class || '']
  }, [h('path', { d })])
}

${lines.join('\n')}
`

// ---- Rails: app/views/icons/_<name>.html.erb, rendered by svg_icon(name, class:) ----
const partials = fs.readdirSync('app/views/icons').filter((f) => f.endsWith('.html.erb'))
const writes = []
for (const file of partials) {
  const name = file.replace(/^_/, '').replace(/\.html\.erb$/, '').replace(/_/g, '-')
  if (keep[name]) continue
  if (!map[name]) { errors.push(`partial app/views/icons/${file} (${name}) is not in lib/icons/mapping.json`); continue }
  const full = path.join('app/views/icons', file)
  const tag = fs.readFileSync(full, 'utf8').replace(/<%.*?%>/g, '').match(/<svg[^>]*>/)[0]
  const size = tag.match(/\swidth="(\d+)"/) ? ` width="${tag.match(/\swidth="(\d+)"/)[1]}" height="${tag.match(/\sheight="(\d+)"/)[1]}"` : ''
  const hidden = tag.includes('aria-hidden="true"') ? ' aria-hidden="true"' : ''
  writes.push([full, `<svg xmlns="http://www.w3.org/2000/svg"${hidden} class="ph-icon <%= local_assigns[:class] %>"${size} viewBox="0 0 256 256" fill="currentColor">
  <path d="${pathData(map[name])}"></path>
</svg>
`])
}

if (errors.length) {
  console.error(errors.join('\n'))
  process.exit(1)
}
fs.mkdirSync('app/javascript/icons', { recursive: true })
fs.writeFileSync('app/javascript/icons/index.js', adapter)
for (const [file, body] of writes) fs.writeFileSync(file, body)
console.log(`app/javascript/icons/index.js: ${vueNames.size} components; app/views/icons: ${writes.length} partials written, ${partials.length - writes.length} kept`)
